BestBeans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coffee.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coffee/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.RoasterListView.as_view(), name='roasters'),
    path('roaster/<int:pk>', views.RoasterDetailView.as_view(), name='roaster-detail'),
    path('beans', views.BeansListView.as_view(), name='beans'),
    path('bean/<int:pk>', views.BeanDetailView.as_view(), name='bean-detail'),
]

coffee/models.py
from functools import reduce

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Roaster(models.Model):
    name = models.CharField(max_length=150)
    url = models.URLField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('roaster-detail', args=[str(self.id)])


class Bean(models.Model):
    name = models.CharField(max_length=100)
    roaster = models.ForeignKey(Roaster, on_delete=models.CASCADE)
    country_of_origin = models.CharField(max_length=100)
    region = models.CharField(max_length=100, null=True)
    varietal = models.CharField(max_length=50, null=True)
    processing_method = models.CharField(max_length=100, null=True)
    tasting_notes = TaggableManager()

    ROAST_LEVELS = (
        ('l', 'Light'),
        ('m', 'Medium'),
        ('md', 'Medium Dark'),
        ('d', 'Dark'),
    )

    roast_level = models.CharField(max_length=2, choices=ROAST_LEVELS, help_text='Roast Level')

    def get_average_rating(self):
        ratings = self.rating_set.all()
        if ratings:
            return reduce(lambda x, y: x.score + y.score, ratings) / len(ratings)
        return ""

    def __str__(self):
        return self.name + " by " + self.roaster.name

    def get_absolute_url(self):
        return reverse('bean-detail', args=[str(self.id)])


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    bean = models.ForeignKey(Bean, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=2, decimal_places=1, validators=[MinValueValidator(0), MaxValueValidator(5)])
    comments = models.TextField()

    def get_title(self):
        if self.title:
            return self.title
        return self.comments[:50]

    def __str__(self):
        return self.score.__str__() + " - " + self.get_title() + " by " + self.user.username

coffee/views.py
from django.db.models import Q

from django.views import generic

from coffee.models import Roaster, Bean

from django.core.exceptions import ImproperlyConfigured

from.filters import BeanFilter

class ListFilteredMixin(object):
    """
    Mixin that adds support for django-filter
    """

    filter_set = None

    def get_filter_set(self):
        if self.filter_set:
            return self.filter_set
        else:
            raise ImproperlyConfigured(
                "ListFilterMixin requires either a definition of "
                "'filter_set' or an implementation of 'get_filter()'")

    def get_filter_set_kwargs(self):
        """
        Returns the keyword arguments for instanciating the filterset.
        """
        return {
            'data': self.request.GET,
            'queryset': self.get_base_queryset(),
        }

    def get_base_queryset(self):
        """
        We can decided to either alter the queryset before or after applying the
        FilterSet
        """
        return super(ListFilteredMixin, self).get_queryset()

    def get_constructed_filter(self):
        # We need to store the instantiated FilterSet cause we use it in
        # get_queryset and in get_context_data
        if getattr(self, 'constructed_filter', None):
            return self.constructed_filter
        else:
            f = self.get_filter_set()(**self.get_filter_set_kwargs())
            self.constructed_filter = f
            return f

    def get_queryset(self):
        return self.get_constructed_filter().qs

    def get_context_data(self, **kwargs):
        kwargs.update({'filter': self.get_constructed_filter()})
        return super(ListFilteredMixin, self).get_context_data(**kwargs)


class RoasterListView(generic.ListView):
    model = Roaster


class RoasterDetailView(generic.DetailView):
    model = Roaster


class BeansListView(ListFilteredMixin, generic.ListView):
    filter_set = BeanFilter
    model = Bean

class BeanDetailView(generic.DetailView):
    model = Bean

coffee/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
        <title>Best Beans</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 {% comment %}   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>{% endcomment %}

    <!-- Add additional CSS in static file -->
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Best Beans</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'roasters' %}">Roasters <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'beans' %}">Beans <span class="sr-only"></span></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="beans" method="get">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" value="Search" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main" class="container">

    <div class="row">
        <div class="col-sm-12 ">
            {% block content %}

            {% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>

</main>

</body>

</html>

coffee/templates/coffee/bean_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Name: {{ bean.name }}</h1>
    <div>
        <h4>Roast: {{ bean.get_roast_level_display }}</h4>
        <h4>Country of Origin: {{ bean.country_of_origin }}</h4>
    </div>
    <h4>Average Rating: {{ bean.get_average_rating }} ({{ bean.rating_set.count }})</h4>
    {% for rating in bean.rating_set.all %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ rating.score }} - {{ rating.get_title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">by: {{ rating.user.username }}</h6>
                <p class="card-text">{{ rating.comments }}</p>
            </div>
        </div>
    {% endfor %}

{% endblock %}

coffee/templates/coffee/bean_list.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block title %}
    <title>Best Beans|Beans</title>
{% endblock %}

{% block content %}
    <div class="main-content">
        <h1>Beans</h1>
        <div class="container">
            <form method="get">
                {% bootstrap_form filter.form field_class='form-check form-check-inline' %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
        {% if bean_list %}
            {% include 'coffee\beans_list_partial.html' with beans=bean_list %}
        {% endif %}
    </div>
{% endblock %}

coffee/templates/coffee/beans_list_partial.html
<div class="row">
    {% for bean in beans %}
        <div class="col-md-4">
            <div class="card shadow-sm p-2 mb-5 bg-white rounded">
                <img src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22288%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20288%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164e68ee99d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164e68ee99d%22%3E%3Crect%20width%3D%22288%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2296.8359375%22%20y%3D%22118.8%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                     alt="" class="card-img-top">
                <div class="card-body">
                    <p class="card-text">
                    <h5><a href="{{ bean.get_absolute_url }}">{{ bean.name }}</a></h5>
                    <h6>By: <a href="{{ bean.roaster.get_absolute_url }}">{{ bean.roaster.name }}</a></h6>
                    <h6>Rating: {{ bean.get_average_rating }} ({{ bean.rating_set.count }})</h6>

                    <hr>
                    <p>Roast: {{ bean.get_roast_level_display }}</p>
                    <p>Origin: {{ bean.country_of_origin }}</p>
                    <p>{% for tag in bean.tasting_notes.all %}
                        <span class="badge badge-pill badge-secondary">{{ tag.name }}</span>
                    {% endfor %}</p>
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
</div>

coffee/templates/coffee/roaster_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Name: {{ roaster.name }}</h1>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Beans</h4>
        {% include 'coffee\beans_list_partial.html' with beans=roaster.bean_set.all %}
    </div>

{% endblock %}

coffee/templates/coffee/roaster_list.html
{% extends "base_generic.html" %}

{% block title %}
    <title>Best Beans|Roasters</title>
{% endblock %}

{% block content %}
    <div class="main-content">
        <h1>Roasters</h1>

        {% if roaster_list %}
            <div class="list-group list-group-flush ">
                {% for roaster in roaster_list %}
                    <div class="list-group-item list-group-item-action">
                        <h3>{{ roaster.name }}</h3>
                        <div class="btn-group" role="group">
                            <a class="btn btn-primary" href="{{ roaster.url }}" target="_blank">Visit</a>
                            <a class="btn btn-primary" href="{{ roaster.get_absolute_url }}">Details/Beans</a>
                        </div>
                    </div>
                {% endfor %}

            </div></div>
        {% endif %}
{% endblock %}